develop of backup

diff --git a/roles/backup/templates/validate-backup-cmd.sh.j2 b/roles/backup/templates/validate-backup-cmd.sh.j2
--- a/roles/backup/templates/validate-backup-cmd.sh.j2
+++ b/roles/backup/templates/validate-backup-cmd.sh.j2
@@ -25,10 +25,22 @@ rsync\ --server\ --sender*)
 {# sudo $SSH_ORIGINAL_COMMAND #}
 {# $SSH_ORIGINAL_COMMAND #}
 SSH_COMMAND="$SSH_ORIGINAL_COMMAND"
+if [[ $string == *"My long"* ]]; the
 # https://stackoverflow.com/questions/13210880/replace-one-substring-for-another-string-in-shell-script
 # Ta bort kommadnot rsync, så vi kan köra det med fler argument nedan.
 SSH_COMMAND="${SSH_COMMAND/rsync /}"
-# There must be a starting / in rsnapshot conf, so remove the first from __backuproot__-replacement:
+# Kör rimligtheskoll om det är i backuprooten. ingen säkerhetsfeature eftersom du kan ange __backuproot__ som en exclude eller liknande, om du vill komma runt det.
+if [[ $SSH_COMMAND != *"__backuproot__"* ]]; then
+  echo "Rejected rsync, not in __backuproot__"
+  echo "$(date "+[%F %T]") Rejected rsync, not in __backuproot__: $SSH_ORIGINAL_COMMAND" >> "$LOG_ERROR"
+  exit 1
+fi
+if [[ $SSH_COMMAND == *".."* ]]; then
+  echo "Rejected rsync, contains '..'"
+  echo "$(date "+[%F %T]") Rejected rsync, contains '..': $SSH_ORIGINAL_COMMAND" >> "$LOG_ERROR"
+  exit 1
+fi
+# There must be a starting / in rsnapshot conf, so remove the first / from __backuproot__-replacement:
 BACKUP_ROOT="{{ script_output_dir[1:] }}"
 # Ersätt med backuprooten:
 SSH_COMMAND="${SSH_COMMAND//__backuproot__/$BACKUP_ROOT}"
@@ -36,6 +48,7 @@ echo "Command to run: rsync --exclude '*__nobackup__*' --exclude '.ssh' $SSH_COM
 # Vi gör det här istället för i variabler: http://mywiki.wooledge.org/BashFAQ/050
 # Filer med __nobackup__ i sig ska aldrig gå att ta backup på.
 rsync --exclude '*__nobackup__*' --exclude '.ssh' $SSH_COMMAND
+exit 0
 ;;
 
 
@@ -78,14 +91,6 @@ echo "Rejected prepare backup"
 echo "$(date "+[%F %T]") Rejected prepare backup: $SSH_ORIGINAL_COMMAND" >> "$LOG_ERROR"
 exit 1
 ;;
-{# TODO: Separera mellan olika backupdest-hosts #}
-{% if backupscripts.stdout_lines is defined %}
-{%   for instance in backupscripts.stdout_lines %}
-{{     instance }})
-{{     backup_info.source_user.home }}/scripts/{{ instance }}
-;;
-{%   endfor %}
-{% endif %}
 
 *)
 echo "Rejected"
